monitorv2 {
	output = eDP-1
	mode = highres
	position = 0x0
	scale = 1.33
}

monitor = HDMI-A-1, 4096x2160@60.00Hz, auto-up, 2, bitdepth, 10, cm, auto

input:touchpad {
	disable_while_typing = false
	scroll_factor = 0.5
	drag_lock = 2
}

gestures {
	workspace_swipe_invert = false
	workspace_swipe_forever = true
	workspace_swipe_distance = 150
	workspace_swipe_direction_lock = false
	workspace_swipe_create_new = false
}

gesture = 2, pinchin, mod: SUPER, cursorZoom, 1.75, mult
gesture = 2, pinchout, mod: SUPER, cursorZoom, 0.25, mult
# gesture = 4, swipe, scale: 100.0, move
gesture = 4, down, fullscreen
gesture = 4, down, mod: SHIFT, fullscreen, maximize
